version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
      timezone: "Australia/Brisbane"
    allow:
      - dependency-type: direct
    labels:
      - "automerge"
      - "dependencies"
    open-pull-requests-limit: 10
