version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
      time: "12:05"
      timezone: "Australia/Brisbane"
    allow:
      - dependency-type: direct
    labels:
      - "automerge"
    open-pull-requests-limit: 10
