# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 10.x
    displayName: Install Node.js

  # this may no-longer be needed because i've installed the puppeteer package
  # which installs its own version of chromium
  # - script: |
  #     sudo apt-get install libxss1 libappindicator1 libindicator7
  #     wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  #     sudo apt install ./google-chrome*.deb
  #   displayName: Install Chrome

  - task: Npm@1
    inputs:
      command: install
    displayName: npm install


  - script: npm run build
    displayName: build the workbench client

  - script: |
      npm test -- --watch=false --code-coverage --browsers FirefoxHeadless,ChromeHeadless
    displayName: Run the test suite

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: "cobertura"
      summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/coverage/workbench-client/cobertura-coverage.xml"
      failIfCoverageEmpty: true
    condition: succeededOrFailed()
    displayName: 'Publish code coverage results'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: "JUnit"
      testResultsFiles: "**/TESTS-*.xml"
      mergeTestResults: true
      publishRunAttachments: true
    displayName: Publish test results

  - script: npm run lint
    condition: succeededOrFailed()
    displayName: Lint project
