# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 10.x
    displayName: Install Node.js

  - task: Npm@1
    inputs:
      command: install
    displayName: npm install

  - script: |
      npm test -- --watch=false --code-coverage --browsers FirefoxHeadless,ChromeHeadless
    displayName: Run the test suite

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: "cobertura"
      summaryFileLocation: "$(Build.SourcesDirectory)/coverage/workbench-client/cobertura-coverage.xml"
      failIfCoverageEmpty: true
    condition: succeededOrFailed()
    displayName: "Publish code coverage results"

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: "JUnit"
      testResultsFiles: "**/TESTS-*.xml"
      mergeTestResults: true
      publishRunAttachments: true
    displayName: Publish test results

  - script: npm run stats
    displayName: "Analyze workbench client bundle"

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: "$(Build.SourcesDirectory)/dist/workbench-client/stats-*.json"
      artifactName: analysis
    displayName: "Publish analysis"

  - task: DeleteFiles@1
    inputs:
      SourceFolder: "$(Build.SourcesDirectory)/dist/**/*"
    displayName: "Cleanup analysis files"

  - script: npm run build
    displayName: "Build the workbench client"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(Build.SourcesDirectory)/dist/**/*"
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/workbench-client.zip"
    displayName: "Zip workbench files"

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: "$(Build.ArtifactStagingDirectory)/workbench-client.zip"
      artifactName: workbench-client
    displayName: "Publish build files"

  - script: npm run lint
    condition: succeededOrFailed()
    displayName: Lint project
