name: "auto-merge"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  merge:
    runs-on: ubuntu-latest
    name: auto-merge
    # needs: [test, e2e, build]

    steps:
      - name: Integration check
        uses: squalrus/merge-bot@v0.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          test: true
          reviewers: false
          labels: automerge
          checks_enabled: false
          method: squash
        if: github.ref === refs/heads/fix-ci
