name: Build Size Diff

on: [pull_request]

jobs:
  diff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # https://github.com/preactjs/compressed-size-action
      - uses: preactjs/compressed-size-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          strip-hash: "\\.(\\w{20})\\."
          pattern: "dist/**/*.{css,js,json,html}"
