name: "Linux"

on: "push"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Update system
        run: apt-get install libxss1 libappindicator1 libindicator7 && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && apt install ./google-chrome*.deb -y

      - name: NPM install
        run: npm install

      - name: Run test suite
        run: npm run test:pipeline

      - name: Run e2e test suite
        run: npm run e2e"

      - name: Build the workbench client
        run: npm run build

      - #: 'Note: This is a third party action: https://github.com/marketplace/actions/create-zip-file'
        name: Zip workbench files
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ${{ env.Build.ArtifactStagingDirectory }}/workbench-client.zip ${{ env.Build.SourcesDirectory }}/dist/workbench-client/

      - name: Publish build files
        uses: actions/upload-artifact@v2
        with:
          path: ${{ env.Build.ArtifactStagingDirectory }}/workbench-client.zip
          name: workbench-client

      - name: Lint project
        run: npm run lint
