name: "Publish Docker Container"

on:
  workflow_run:
    workflows: ["Build, Test, and Publish"]
    types:
      - completed
  
jobs:
  publish:
    name: "Publish Docker Container"
    runs-on: "ubuntu-latest"
    needs: ["test", "build"]
    # only on tag or commit to master
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      (github.ref == 'refs/heads/master' || contains(github.ref, 'refs/tag'))
    steps:
      - uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: qutecoacoustics/workbench-client
          # this repo is superseding the current workbench-client container,
          # however currently they both exist.
          tags: beta
          tag_with_ref: true
          tag_with_sha: true
          path: .
          add_git_labels: true
          push: true
