### This workflow is not part of the main workflow so that dependabot
### is able to access repo secrets

name: "Publish Unit Tests Results"

on:
  workflow_run:
    workflows: ["Build, Test, and Publish"]
    types:
      - completed

steps:
  publish:
    name: "Publish Unit Tests Results"
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: artifacts/**/TESTS-*.xml
          report_individual_runs: true
          deduplicate_classes_by_file_name: true
