name: "Publish Docker Container"

on:
  workflow_run:
    workflows: ["Build, Test, and Publish"]
    types:
      - completed

jobs:
  publish:
    name: "Publish Docker Container"
    runs-on: "ubuntu-latest"
    # only on tag or commit to master
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      (github.ref == 'refs/heads/master' || contains(github.ref, 'refs/tag'))
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        shell: pwsh
        run: ./build/build_docker.ps1
