name: "Windows"

on: "push"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Update system
        run: sudo apt update && sudo apt upgrade -y

      - name: NPM install
        run: npm install

      - name: Run test suite
        run: npm run test:pipeline

      - name: Run e2e test suite
        run: npm run e2e"

      - name: Lint project
        run: npm run lint
