name: "Build, Test, and Publish"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Unit Tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: NPM install
        run: npm install

      - name: Run test suite on chrome
        run: npm run test:pipeline -- --browsers ChromeHeadless

      - name: Run test suite on firefox
        run: npm run test:pipeline -- --browsers FirefoxHeadless

      - name: Run test suite on edge
        run: npm run test:pipeline -- --browsers EdgeHeadless
        if: matrix.os == 'windows-latest'

      - name: Lint project
        run: npm run lint

  e2e:
    name: E2E Tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: NPM install
        run: npm install

      - name: Run e2e test suite
        run: npm run e2e

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: NPM install
        run: npm install

      - name: Build the workbench client
        run: npm run build

      - #: 'Note: This is a third party action: https://github.com/marketplace/actions/create-zip-file'
        name: Zip workbench files
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./workbench-client.zip ./dist/workbench-client/

      - name: Publish build files
        uses: actions/upload-artifact@v2
        with:
          path: ./workbench-client.zip
          name: workbench-client

  merge:
    runs-on: ubuntu-latest
    name: auto-merge
    # needs: [test, e2e, build]

    steps:
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      - name: Integration check
        uses: squalrus/merge-bot@v0.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          test: true
          reviewers: false
          labels: automerge
          checks_enabled: false
          method: squash
        if: github.ref == "refs/heads/fix-ci"
