env:
  npm_config_cache: ${{ env.Pipeline.Workspace }}/.npm

jobs:
  build:
    runs-on: ${{ matrix.imageName }}

    strategy:
      matrix:
        imageName:
          - ubuntu-latest
          - macOS-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: NPM install
        run: npm install

      - name: Run test suite
        run: npm run test:pipeline

      - name: Run e2e test suite
        run: npm run e2e"

      - name: Build the workbench client
        run: npm run build
        if: and(success(),eq(variables['Agent.OS'], 'linux'))

      - #: 'Note: This is a third party action: https://github.com/marketplace/actions/create-zip-file'
        name: Zip workbench files
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ${{ env.Build.ArtifactStagingDirectory }}/workbench-client.zip ${{ env.Build.SourcesDirectory }}/dist/workbench-client/
        if: and(success(),eq(variables['Agent.OS'], 'linux'))

      - name: Publish build files
        uses: actions/upload-artifact@v2
        with:
          path: ${{ env.Build.ArtifactStagingDirectory }}/workbench-client.zip
          name: workbench-client
        if: and(success(),eq(variables['Agent.OS'], 'linux'))

      - name: Lint project
        run: npm run lint
